notifications:
  email: false
sudo: required
language: node_js
node_js:
  - "7.8"
before_script:
  - npm install --global lighthouse
  - lighthouse --output=json --output-path=./lighthouse.json localhost:3000
  - npm run release
script:
  - npm run release
