notifications:
  email: false
sudo: required
language: node_js
node_js:
  - "7.8"
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - yarn build
  - yarn start &
  - npm install -g lighthouse
  - lighthouse --version
  - git clone https://github.com/GoogleChrome/lighthouse.git
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - mv lighthouse/lighthouse-core/scripts/download-chrome.sh .
  - ./download-chrome.sh
  - 
script:
  - lighthouse http://localhost:3000 --output=json --output-path=./validator/lighthouse.json 
  - node ./validator/validator.js ./validator/lighthouse.json
