notifications:
  email: false
sudo: required
language: node_js
node_js:
  - "7.8"
before_script:
  - "export DISPLAY=:99.0"
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - "sh -e /etc/init.d/xvfb start"
  - npm explore -g lighthouse -- ./lighthouse-core/scripts/download-chrome.sh
  - npm run build
script:
  - npm run start &
  - lighthouse --output=json --output-path=./validator/lighthouse.json localhost:3000
  - node ./validator/validator.js ./validator/lighthouse.json
